### ISSUE TITLE
POST request to https://api.metanetworks.com/v1/oauth/token failed with status code 401: Unauthorized

### ISSUE THREAD

**Issue by lce12** [nsofnetworks/terraform-provider-pfptmeta#39]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by hod-alpert** [comment]
Hi.
It seems like a misuse issue.
Did you configure the client with api key id / secret + org short name like recommended [here](https://registry.terraform.io/providers/nsofnetworks/pfptmeta/latest/docs)?

**Comment by berkil** [comment]
Yes I did.
And what do you mean by misuse issue?

**Comment by hod-alpert** [comment]
I mean that it must be wrong configuration of the provider.
Which configuration did you use?
explicit configuration in the terraform file?
env variables? or json file?
Can you check for spelling issues?
If no spelling issues found, can you provide the `api_key` and `org_shortname` you are using?
Also I see you're using a pretty old version, can you migrate to the latest?

**Comment by berkil** [comment]
I used explicit configuration in terraform file.
Here is an example:

```
resource "pfptmeta_posture_check" "macOS_min_os_version_check" {
  name = "MacOS Minimal OS Version"
  description = "MacOS minimal OS version posture check"
  apply_to_org = true
  exempt_entities = var.exempt_entities
  osquery = local.macOS_min_os_version_check
  platform = "macOS"
  enabled = true
  action = "NONE"
  when = ["PRE_CONNECT"]
  user_message_on_fail = "You MacOS needs to be updated to at least version
${var.posture_checks["macOS_min_os_version_check"]}"
}
```



For the Action I want to use `WARNING` option which is available in the UI-
but not in the TF provider
The org short name is payuzooz, the token I will not share over email for
obvious reasons

What do you mean I use the old version?

**Comment by hod-alpert** [comment]
@berkil 
You're using the `0.1.14` version, the latest version is `0.1.27`

Can you try rotating the secret of the key and run it again?
I'll then try to look at the logs and see if something comes up.

**Comment by hod-alpert** [comment]
Right.. that explains a bit. waiting for @lce12 to respond

**Comment by hod-alpert** [comment]
Closing for now, @lce12 feel free to reopen if the issue comes back up.
