### ISSUE TITLE
Support mapped service attachment on metaport cluster resources

### ISSUE THREAD

**Issue by uristernik** [nsofnetworks/terraform-provider-pfptmeta#54]
Hi there, we need one of the mapped services we create to be attached to different MetaPort cluster. 
For example, we create 3 mapped service with host names X Y API. We want X, Y to be attached to the MetaPort cluster created in the terraform above, and host name API to be attached to different MetaPort cluster created elsewhere.

### Terraform Version
v1.2.8

### Affected Resource(s)
- pfptmeta_metaport_cluster

### Terraform Configuration Files
```
resource "pfptmeta_metaport" "metaport" {
  count = local.metaport_config["enable_meta"] ? 2 : 0
  name  = format("%s-%s", local.metaport_name, count.index)
}

resource "pfptmeta_network_element" "mapped-service" {
  count = local.metaport_config["enable_meta"] ? 6 : 0
  name = "hostname-${count.index}"
  description  = "${local.resource_hostnames[count.index]}"
  mapped_service = "${local.resource_hostnames[count.index]}"
}

resource "pfptmeta_network_element_alias" "alias" {
  count = local.metaport_config["enable_meta"] ? 6 : 0
  network_element_id = pfptmeta_network_element.mapped-service[count.index].id
  alias = "${local.resource_hostnames[count.index]}"
}

resource "pfptmeta_network_element" "mapped-service-api" {
  count = local.metaport_config["enable_meta"] ? 1 : 0
  name = "${api.url}"
  description = "${api.url} DESC"
  mapped_service = "${api.url}"
}

resource "pfptmeta_metaport_mapped_elements_attachment" "attachment" {
  count = local.metaport_config["enable_meta"] ? 1 : 0
  metaport_id = **pfptmeta_metaport_cluster.different_metaport_cluster.id**
  mapped_elements = toset(flatten([pfptmeta_network_element.mapped-service-api[0].id]))
}

resource "pfptmeta_metaport_cluster" "metaport_cluster" {
  count = local.metaport_config["enable_meta"] ? 1 : 0
  name = "${resource.name}-MetaPort-cluster"
  description = "${resource.name}"
  metaports = toset(pfptmeta_metaport.metaport[*].id)
  mapped_elements = toset(pfptmeta_network_element.mapped-service[*].id)
}
```

### Debug Output
```
╷
│ Error: "mpc-***" should have a prefix of [mp]
│
│   with pfptmeta_metaport_mapped_elements_attachment.attachment,
│   on meta.tf line 123, in resource "pfptmeta_metaport_mapped_elements_attachment" "attachment":
│  123:   metaport_id     = pfptmeta_metaport_cluster.metaport_cluster.id
│
╵
```

### Expected Behavior
Mapped service will connect to MetaPort cluster.

### Actual Behavior
We get an error. It appears it is looking for MetaPorts and fails on MetaPorts clusters

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Running in EC2 Classic.

**Comment by hod-alpert** [comment]
Hi @uristernik Thanks for contacting us, the request has been added to our backlog and we will update once its completed

**Comment by uristernik** [comment]
Any updates on that ? @hod-alpert

**Comment by hod-alpert** [comment]
@uristernik 
I believe a new version will be ready at the beginning of next week with this feature.

**Comment by hod-alpert** [comment]
@uristernik version 0.1.30 is out.
check out the new [resource](https://registry.terraform.io/providers/nsofnetworks/pfptmeta/latest/docs/resources/metaport_cluster_mapped_elements_attachment)
