### ISSUE TITLE
Resource pfptmeta_policy should support ab ( log streamers) as sources as well.

### ISSUE THREAD

**Issue by bnayah** [nsofnetworks/terraform-provider-pfptmeta#73]
Hello, the validation logic in the file:

https://github.com/nsofnetworks/terraform-provider-pfptmeta/blob/master/internal/provider/policy/resource.go

It should be amended to support the "ab" prefix, similar to the UI/Console/API.

Currently, we need to manage our log streamer policy manually. 

Thank you.

**Comment by kvitali** [comment]
@bnayah your observation is correct, we will fix that

**Comment by gfleischer-meta** [comment]
@bnayah thanks for the input,
the issue has been fixed.
you can use the new version 0.1.41 with a fix for this issue.

**Comment by bnayah** [comment]
Thank you for the quick response.  I have upgraded the provider and it is working perfectly. 🥇
